tetris : tetris.c 
	gcc -o tetris tetris.c -I../sjh/sjh_header -I/home/shinjaeho/sjh/sjh_hjh/hjh/hjh_header -L../sjh/sjh_src -lfuncs -L/home/shinjaeho/sjh/sjh_hjh/hjh/hjh_src -lhjh
clean :
	rm tetris
